# Generated by Django 3.1.1 on 2023-06-24 10:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('STUDENT', 'STUDENT')], default='ADMIN', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_abregee', models.CharField(max_length=100)),
                ('date_cree', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('professeur', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en cours', 'en cours'), ('fini', 'fini'), ('commence', 'commence'), ('en attente', 'en attente')], max_length=10)),
                ('date_debut', models.DateField(auto_now=True)),
                ('date_fini', models.DateField(auto_now=True)),
                ('date_cree', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.CharField(max_length=100)),
                ('annee_fin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=100)),
                ('telephone_etudiant', models.IntegerField(blank=True, null=True)),
                ('telephone_parent', models.IntegerField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='student_default_image.png', upload_to='student_image')),
                ('date_de_naissance', models.CharField(blank=True, max_length=25, null=True)),
                ('immatriculation', models.CharField(max_length=20)),
                ('classe', models.CharField(choices=[('L1', 'Licence I'), ('L2', 'Licence II'), ('L3', 'Licence III')], max_length=15)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('date_dernier_modification', models.DateField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filiere')),
                ('modules', models.ManyToManyField(blank=True, to='app.Module')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0)),
                ('date_cree', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='staff_default_image.png', upload_to='staff_image')),
                ('adresse', models.TextField()),
                ('sexe', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('date_cree', models.DateTimeField(auto_now_add=True)),
                ('date_modifie', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(to='app.Module')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnom', models.CharField(blank=True, max_length=20, null=True)),
                ('background_image', models.ImageField(default='technosup_background_image.png', upload_to='background_image')),
                ('description_profile', models.TextField(blank=True, help_text='Decrivez un peu de vous... votre personnalite, votre ambitions, etc', max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filiere',
            name='modules',
            field=models.ManyToManyField(blank=True, to='app.Module'),
        ),
    ]
