# Generated by Django 3.1.1 on 2023-07-09 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230624_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_message', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('destinataire_email', models.EmailField(max_length=254)),
                ('date_cree', models.DateTimeField(auto_now_add=True)),
                ('envoyeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
