# Generated by Django 3.1.1 on 2023-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.IntegerField(default=7277),
            preserve_default=False,
        ),
    ]
