# Generated by Django 3.1.1 on 2023-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_lu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
