# Generated by Django 3.1.1 on 2023-07-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='motive_message',
        ),
    ]
